### PR TITLE
FOSSA config file added

### PR DESCRIPTION
**Pull request by idvoretskyi**
Fixes https://github.com/servicemeshinterface/smi-spec/issues/183

Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>

### CODE REVIEW

**Comment by idvoretskyi** [comment]
/hold

Trying to understand why the FOSSA scan fails =/

**Comment by stefanprodan** [comment]
@idvoretskyi this repo has no source code, just documentation. I think it makes sense to add FOSSA to smi-sdk-go, smi-metrics and smi-adapter-istio.

**Comment by idvoretskyi** [comment]
@stefanprodan I'm already on them, thanks :)

**Comment by idvoretskyi** [comment]
UPD. This repo includes md files only, no need to scan here :)

**Pull request closed without merging**
