### PR TITLE
ref(TrafficTarget): update requirements for TrafficTarget

### PR DESCRIPTION
**Pull request by michelleN**
Resolves #188 

Slack thread: https://cloud-native.slack.com/archives/C0105GB1BJQ/p1600760173001900

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]

**Review by SantoDE — DISMISSED** [review]
LGTM ;-)

**Comment by stefanprodan** [comment]
@michelleN can you please fix:
```
**Compatible With:** specs.smi-spec.io/v1alpha4-WD
```

**Review by stefanprodan — APPROVED** [review]

**Review by lachie83 — APPROVED** [review]

**Review by bridgetkromhout — APPROVED** [review]

**Comment by bridgetkromhout** [comment]
Looks like this clarifies it - thanks, @michelleN!

**Comment by leecalcote** [comment]
This _must_ makes much sense. This statement reinforces that there are three required elements of what comprises a TrafficTarget. ✔️

**Review by leecalcote — APPROVED** [review]

**Review by stefanprodan — APPROVED** [review]

**Pull request merged**
