### PR TITLE
TrafficSplit: Clarify root service can be any addressable name that resolves to an application accessible by the mesh

### LINKED ISSUE #215: Clarify SMI root/apex service does not need to be a Kubernetes service
We came across this paragraph in the traffic split spec while working on OSM and think it might warrant some clarification:
> The resource is associated with a root service. This is referenced via spec.service. The spec.service name is the FQDN that applications will use to communicate. For any clients that are not forwarding their traffic through a proxy that implements this proposal, the standard Kubernetes service configuration would continue to operate.

It is clear that the root service should be an FQDN but then the sentence about following standard Kubernetes service configuration might make someone think that the root service needs to be a Kubernetes service. As we understand this part of the spec, we do not think the FQDN needs to reference a Kubernetes service and the spec should explicitly have a line that states this. The reason is because a client should be able to reference any FQDN whether that be foo.com or a Kubernetes service bookstore.bookstore-ns where bookstore is the name of the Kubernetes service and bookstore-ns is the name os the Kubernetes namespace the service runs in.

### PR DESCRIPTION
**Pull request by johnsonshi**
TrafficSplit: Clarify root service can be any addressable name that resolves to an application accessible by the mesh

This clarifies that the TrafficSplit root
can be referenced through an FQDN.
The TrafficSplit root FQDN can either be a
(1) Kubernetes service that resolves
to the FQDN (such as service.service-namespace)
(2) other FQDNs (such as foo.com)

Resolves #215.

Signed-off-by: Johnson Shi <Johnson.Shi@microsoft.com>

### CODE REVIEW

**Comment by johnsonshi** [comment]
@michelleN I've opened this PR to address #215.

**Review by stefanprodan — CHANGES_REQUESTED** [review]
The name of this PR is misleading. This is not just a clarification as it breaks the current API **v1alpha4** and all its implementations in a backwards incompatible manner.

**Comment by michelleN** [comment]
@stefanprodan - I can see where you're coming from. This proposal came from a conversation that @johnsonshi and I had about TrafficSplit. I asked him to open a PR with the change so we could use it to discuss. This can probably be broken into two PRs (1) Clarifying that the root service does not need to be a Kubernetes service and (2) The proposed change of changing the service key to "fqdn". Thoughts on this are welcome.

**Comment by stefanprodan** [comment]
@michelleN this PR went in the opposite direction, we already released v1alpha4 https://github.com/servicemeshinterface/smi-sdk-go/tree/main/pkg/apis/split/v1alpha4 so such a change can't happen here but in v1alpha5. I also think we should't be renaming fields, in v1alpha5 we could add the `fqdn` field and mark `service` as deprecated, then in a couple of month we could release v1alpha6 that drops `service`.

**Comment by stefanprodan** [comment]
Maybe a better option would be to point the `service` to a Kubernetes service that has a external name, this way we don't break the API https://kubernetes.io/docs/concepts/services-networking/service/#externalname

**Comment by johnsonshi** [comment]
Hi @michelleN and @stefanprodan, as per the last SMI community meeting, we decided to split up this PR into two. This PR is the first one, which is the uncontroversial PR that clarifies the language. We can open another PR (replacing `spec.service` with `spec.fqdn`) after this PR is merged.

image

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @johnsonshi

**Comment by stefanprodan** [comment]
@johnsonshi @michelleN have you considered my proposal?

> Maybe a better option would be to point the service to a Kubernetes service of type ExternalName, this way we don't break the SMI API https://kubernetes.io/docs/concepts/services-networking/service/#externalname

**Comment by johnsonshi** [comment]
That's a great idea @stefanprodan. I'll look up info on k8s ExternalName services and see what can be done. Thanks!

**Comment by michelleN** [comment]
@stefanprodan - I don't think we'd be breaking the SMI API by updating this language. I think the original intention was always to use the service key as an fqdn the way @johnsonshi has described. Please correct me if I'm wrong @grampelberg @nicholasjackson and others. I think we'd be making things a little more complicated for the end user by making them use ExternalName Service.

**Comment by nicholasjackson** [comment]
Service was always designed to be a loose coupling in the original spec, this would allow for virtual services that only have meaning to the service mesh, external services such as those running on VMs, and other clusters. As far as I am aware there is no validation that attempts to tie service to a Kubernetes service in any of the current implementations. Not sure we needed to enforce this either as this does not really break the API as it was always a string.

**Comment by nicholasjackson** [comment]
Reading back through this though, are we confident that this needs to be an FQDN? For example, in Consul you can define a service that is addressable just by its name from within the data center (cluster). E.G. `payments`, you can also have a Virtual service in a different data center that is addressable with `payments.datacenter`. There is no requirement to have a TLD for either of these services.

If I were to implement the proposal to the letter I would have to add a fake TLD `.consul` this is not a massive deal but I think could cause confusion for users as the Consul documentation does not use this approach. In addition, specifying the data center in a single DC setup feels like overkill. Realistically what I would probably do in the controller is ignore the FQDN requirement completely as just referencing the service name would work and provides a better UX to the Consul user. Obviously, if we add validation to the CRDs it is not possible to ignore the formatting of FQWDN.

In the instance that the service mesh just supports simple service names and does not support multi-cluster or TLDs, does enforcing FQDN make sense.

I agree with the sentiment in the PR to clean up the use but I honestly think that this just needs to be something like `an addressable name for an application accessible by the service mesh`.

**Comment by michelleN** [comment]
@nicholasjackson Those are really good points and I am for using the wording you suggested.

**Comment by johnsonshi** [comment]
Incorporated wording as suggested by @nicholasjackson into my PR. Thanks!

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @johnsonshi

**Comment by michelleN** [comment]
Thanks @johnsonshi ... We've updated our contributing guidelines to reflect a new process. Contributions / updates to the spec will now be taken on the `draft` branch off of this repository. Once PR #231 is merged, could you PR your changes against the draft branch? Sorry for the trouble.

**Review by michelleN — CHANGES_REQUESTED** [review]
Changes look great @johnsonshi . Thank you.
Could you move these changes to apis/traffic-split/traffic-split.md?

**Comment by johnsonshi** [comment]
@michelleN done.

**Review by michelleN — APPROVED** [review]

**Review by michelleN — COMMENTED** [review]
We can update the version of the document as a follow up

**Review by stefanprodan — APPROVED** [review]

**Pull request merged**
